### ISSUE TITLE
sync-recipes not start with composer install

### ISSUE THREAD

**Issue by viduc** [symfony/flex#880]
Hi,

I have a project in symfony 5.2.
for a few days when i try to reinstall it by composer install (my composer.json is in my git project) i have an error:

Script cache:clear returned with error code 1 !! Could not open input file: ./bin/console
So i try to create a new projetc with symfony new --full. Its ok but if i try to copy composer.json in another empty folder and i start composer install i have the same problem.

I find how to start the recipe with composer sync-recipes -v --force and restart composer install or update after but its not fine... ANd in my project if i do this method, if have a multiple bug in my code (variable not initialize, not present, route not find etc...).

I suppose its flex that have problem but i dont find something on... symfony flex is in 1.18.5

I open an issue on symfony github [here](https://github.com/symfony/symfony/discussions/45597)

I made a reproducer [here](https://github.com/viduc/Bug-45597)

Can you help me?

Thanks

**Comment by mareckigit** [comment]
I have the same problem. Symfony 4.4.39 and Flex 2.1.6. When I run composer recipes -vvv, I see loop in downloading doctrine annotation package. I have downgraded flex version to 2.1.4 and now it works.

**Comment by viduc** [comment]
Thanks for your test. I cant use 2.1.4 cause i'm on php 7 but i try to downgrade version 1, the error come with 1.18.5 (and so with 2.1.5 and more ?)

Thanks for your help

**Comment by mareckigit** [comment]
I can confirm the error on 2.1.5 version. I didn't test more versions. Today we have another problem with recipes. The official end point https://symfony.sh has broken CERT.

**Comment by viduc** [comment]
ok, no problem I fixed my problem by locking the version.
Do you want me to close this issue or keep it open?

**Comment by tarasb81** [comment]
Same problem with loop doctrine/annotation recipies on Symfony 4.4.37. PHP 7.4.8. Problem start after recipies version 1.10 was created.
I try to install older doctrine/annotation and symfony/fles versions, but problen still exist.
